package com.ericsson.deviceaccess.serviceschema.codegenerator.javabuilder;

import com.ericsson.deviceaccess.serviceschema.codegenerator.javabuilder.modifiers.AccessModifier;

/**
 * Implementer defines how code generated by it can be accessed.
 *
 * @author delma
 */
public interface Accessable {

    /**
     * How generated code can be accessed
     *
     * @return AccessModier
     */
    AccessModifier getAccessModifier();

    /**
     * Sets how generated code can be accessed
     *
     * @param modifier AccessModifier to set
     * @return this
     */
    Accessable setAccessModifier(AccessModifier modifier);

}
