package com.ericsson.deviceaccess.serviceschema.codegenerator.javabuilder;

/**
 * Implementer defines parameters that code generated by it can be called with.
 *
 * @author delma
 */
public interface Callable {

    /**
     * Adds parameter to callable
     *
     * @param parameter parameter to be added
     * @return this
     */
    Callable addParameter(Param parameter);

}
