package com.ericsson.deviceaccess.serviceschema.codegenerator;

import java.util.regex.Pattern;

/**
 *
 * @author delma
 */
public class JavaHelper {

//    public static final String GENERATION_WARNING = "THIS IS AUTOMATICALLY GENERATED BY {@link " + JavaBuilder.class.getCanonicalName() + "}.";
    public static final String INDENT = "    ";
    public static final String LINE_END = "\n";
    public static final String STATEMENT_END = ";" + LINE_END;
    public static final String BLOCK_START = "{";
    public static final String BLOCK_END = "}";
    public static final String REPLACEMENT_START = "#";
    public static final String REPLACEMENT_END = ";";
    public static final String PACKAGE = "package";
    public static final String IMPORT = "import";
    private static final String ENDFUL_PATTERN = REPLACEMENT_START + "\\d*" + REPLACEMENT_END;
    private static final String ENDLESS_PATTERN = REPLACEMENT_START + "\\d+";
    public static final Pattern PARAMETER_PATTERN = Pattern.compile("(" + ENDFUL_PATTERN + ")|(" + ENDLESS_PATTERN + ")");

    public static String getGenerationWarning(Class<?> generator, Class<?> caller) {
        return "THIS IS AUTOMATICALLY GENERATED BY {@link " + generator.getCanonicalName() + "} IN REQUEST OF {@link " + caller.getCanonicalName() + "}.";
    }

    public static StringBuilder indent(StringBuilder builder, int indent) {
        while (0 < indent) {
            builder.append(INDENT);
            indent--;
        }
        return builder;
    }

    public static StringBuilder emptyLine(StringBuilder builder) {
        builder.append(LINE_END);
        return builder;
    }

    //TODO: This wrecks camelCasing
    public static String capitalize(String string) {
        StringBuilder sb = new StringBuilder(string.toLowerCase());
        sb.setCharAt(0, Character.toUpperCase(sb.charAt(0)));
        return sb.toString();
    }

}
